"""Imlelment Coffes_Users tabele

Revision ID: b27ef868a48c
Revises: 809323f1fa75
Create Date: 2024-01-08 17:17:35.056125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b27ef868a48c'
down_revision: Union[str, None] = '809323f1fa75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_coffe',
    sa.Column('user_coffe_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('coffe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coffe_id'], ['coffes.coffe_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_coffe_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_coffe')
    # ### end Alembic commands ###
